import type { Metadata } from "next";
import "./globals.css";
import { BeauSans } from "@/utils/fontGenerator";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Oupia Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={BeauSans.className}>
        <Providers>
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
